title: Tiny web pet
hero_image: images/banner.png
description: Create a tiny virtual pet that lives in a web page
listed: false
pdf: false
landing: true
steps:
  - title: 'Step 1'
  - title: 'Step 2'
    completion:
      - 'engaged'
  - title: 'Step 3'
  - title: 'Step 4'
  - title: 'Step 5'
    completion:
      - 'internal'
  - title: 'Step 6'
  - title: 'Step 7'
    challenge: true
    completion:
      - 'external'
  - title: 'Step 8'
    challenge: true
